services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - postgres
        restart: unless-stopped
    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        ports:
            - "9411:9411"
    rabbitmq:
        image: rabbitmq:3.9.11-management-alpine
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"

    eureka-server:
        image: merikbest/twitter-spring-reactjs:eureka-server
        container_name: eureka-server
        environment:
            ZIPKIN_HOST: zipkin
        ports:
            - "8761:8761"

    config-server:
        image: merikbest/twitter-spring-reactjs:config-server
        container_name: config-server
        environment:
            EUREKA_HOST: eureka-server
            ZIPKIN_HOST: zipkin
        ports:
            - "8888:8888"

    topic-service:
       image: merikbest/twitter-spring-reactjs:topic-service
       container_name: topic-service
       environment:
           EUREKA_HOST: eureka-server
           CONFIG_SERVER_HOST: config-server
           DATASOURCE_HOST: postgres
           ZIPKIN_HOST: zipkin
           RABBITMQ_HOST: rabbitmq
       ports:
           - "8003:8003"

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin: