spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/twitter9
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        locations: classpath:db/migration

hostname: http://localhost:3000
jwt:
    header: Authorization
    secret: dejavu
    expiration: 6048000
