server:
    port: 8006
spring:
    application:
        name: chat-service
    datasource:
        url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/chat
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        locations: classpath:db/migration/chat
    zipkin:
        base-url: http://${ZIPKIN_HOST:localhost}:9411
    rabbitmq:
        addresses: ${RABBITMQ_HOST:localhost}:5672

eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: ${EUREKA_HOST:localhost}
