server:
    port: 8003
spring:
    application:
        name: topic-service
    datasource:
        url: jdbc:postgresql://localhost:5432/topic
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        locations: classpath:db/migration/topic
    zipkin:
        base-url: http://localhost:9411
    rabbitmq:
        addresses: localhost:5672

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
