server:
    port: 8002
spring:
    application:
        name: tweet-service
    datasource:
        url: jdbc:postgresql://localhost:5432/twitter9
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        locations: classpath:db/migration
    zipkin:
        base-url: http://localhost:9411
    rabbitmq:
        addresses: localhost:5672

google:
    api:
        url: https://www.googleapis.com/youtube/v3/videos?id=%s&key=%s&part=snippet,contentDetails,statistics,status
        key: AIzaSyBtQYzGSmcCzqOztibg1BgSTqv0xwg1D-M

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
